//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.BAL.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAF.BAL.ResourceFile.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn&apos;t exist or Last Name doesn&apos;t match.
        /// </summary>
        public static string authenticateConformationError {
            get {
                return ResourceManager.GetString("authenticateConformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This subscription is successfully created..
        /// </summary>
        public static string CardSubscription {
            get {
                return ResourceManager.GetString("CardSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction is successfully completed..
        /// </summary>
        public static string CardTransactionSuccessfull {
            get {
                return ResourceManager.GetString("CardTransactionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Failed.
        /// </summary>
        public static string ChangegePasswoResetFaild {
            get {
                return ResourceManager.GetString("ChangegePasswoResetFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn&apos;t match our records.
        /// </summary>
        public static string ChangegePassworVerifyError {
            get {
                return ResourceManager.GetString("ChangegePassworVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer doesn&apos;t match our records.
        /// </summary>
        public static string forgotAnswerNotMatch {
            get {
                return ResourceManager.GetString("forgotAnswerNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account doesn&apos;t match our records.
        /// </summary>
        public static string ForgotConformationError {
            get {
                return ResourceManager.GetString("ForgotConformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is not save.
        /// </summary>
        public static string HttpStatusCodeNotFound {
            get {
                return ResourceManager.GetString("HttpStatusCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we can&apos;t process your payment at this time. Please call Customer Service @ 800-793-9661 ext 600..
        /// </summary>
        public static string LoginAcceptedPaymentsFaild {
            get {
                return ResourceManager.GetString("LoginAcceptedPaymentsFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed..
        /// </summary>
        public static string LoginException {
            get {
                return ResourceManager.GetString("LoginException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Login.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your account hasn&apos;t been registered already..
        /// </summary>
        public static string registeredFaild {
            get {
                return ResourceManager.GetString("registeredFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Successful.
        /// </summary>
        public static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is invalid.
        /// </summary>
        public static string RequestInvalid {
            get {
                return ResourceManager.GetString("RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing number doesn&apos;t exist .
        /// </summary>
        public static string RoutingNumberError {
            get {
                return ResourceManager.GetString("RoutingNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Address is successfully saved..
        /// </summary>
        public static string SaveCardAddress {
            get {
                return ResourceManager.GetString("SaveCardAddress", resourceCulture);
            }
        }
    }
}
