//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.BAL.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAF.BAL.ResourceFile.TextMessages", typeof(TextMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have initiated an AutoPay Enrollment of MAF acct # {0}. Your web confirmation # is {1}. For info reply HELP.
        /// </summary>
        public static string AutoPayAgreement {
            get {
                return ResourceManager.GetString("AutoPayAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your AutoPay Recurring Pmt Enrollment is successful for MAF acct # {0} w/ pmt method ending {1}. Confirmation # is {2}. For info reply HELP or to cancel reply AUTOPAY OFF.
        /// </summary>
        public static string AutoPayEnrollment {
            get {
                return ResourceManager.GetString("AutoPayEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your scheduled pmt of ${0} for MAF acct # {1} on {2}  has been canceled. For info reply HELP.
        /// </summary>
        public static string CancelSchedule {
            get {
                return ResourceManager.GetString("CancelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your AutoPay Enrollment for MAF acct # {0} has been canceled. For info reply HELP.
        /// </summary>
        public static string DeleteAutoPay {
            get {
                return ResourceManager.GetString("DeleteAutoPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your Pay By Text on MAF acct # {0} has been canceled. For info reply HELP.
        /// </summary>
        public static string DeletePayByText {
            get {
                return ResourceManager.GetString("DeletePayByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted out from Chat By Text service from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string DisableChatByText {
            get {
                return ResourceManager.GetString("DisableChatByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted out to rcv Payment Confirmation msgs from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string DisablePaymentConfirmation {
            get {
                return ResourceManager.GetString("DisablePaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted out to rcv Payment Reminder msgs from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string DisablePaymentReminder {
            get {
                return ResourceManager.GetString("DisablePaymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted in for Chat By Text service from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string EnableChatByText {
            get {
                return ResourceManager.GetString("EnableChatByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted in to rcv Payment Confirmation msgs from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string EnablePaymentConfirmation {
            get {
                return ResourceManager.GetString("EnablePaymentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have opted in to rcv Payment Reminder msgs from Mid-Atlantic Finance. For info reply HELP.
        /// </summary>
        public static string EnablePaymentReminder {
            get {
                return ResourceManager.GetString("EnablePaymentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have  scheduled future pmt of ${0} for MAF acct # {1} on {2}. Confirmation # is {3}. For info reply HELP.
        /// </summary>
        public static string FuturePay {
            get {
                return ResourceManager.GetString("FuturePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You have successfully unsubscribed from all Notifications By Text Services and will no longer receive msgs. For info reply HELP.
        /// </summary>
        public static string NotificationsByTextOptOut {
            get {
                return ResourceManager.GetString("NotificationsByTextOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, You&apos;ve requested to make a pmt of ${0} w/ pmt method ending {1}. To complete approval reply CONFIRM. For info reply HELP or to cancel reply PAYBYTEXT OFF.
        /// </summary>
        public static string PayByTextConfirm {
            get {
                return ResourceManager.GetString("PayByTextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your Pay By Text enrollment is successful for MAF acct # {0} w/ pmt method ending {1}. Confirmation # is {2}. For info reply HELP or to cancel reply PAYBYTEXT OFF.
        /// </summary>
        public static string PayByTextEnrollment {
            get {
                return ResourceManager.GetString("PayByTextEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your pmt of ${0} via Pay By Text cannot be processed. Please call Customer Service @ 800-793-9661 ext 600..
        /// </summary>
        public static string PayByTextNotProcess {
            get {
                return ResourceManager.GetString("PayByTextNotProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, MAF Acct #: {0} AmountDue: ${1} Due Date: {2} . Replay PAY or HELP or  or to cancel reply PAYBYTEXT OFF.
        /// </summary>
        public static string PayByTextPay {
            get {
                return ResourceManager.GetString("PayByTextPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your scheduled pmt of ${0} cannot be processed. Please call Customer Service @ 800-793-9661 ext 600..
        /// </summary>
        public static string ScheduledPaymentNotProcess {
            get {
                return ResourceManager.GetString("ScheduledPaymentNotProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Payment of ${0} has been received on MAF acct # {1}. Your confirmation # is {2}. For info reply HELP.
        /// </summary>
        public static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your scheduled payment of ${0} has been received on MAF account # {1}. Confirmation # is {2}. For info reply HELP.
        /// </summary>
        public static string SuccessfulScheduledPayment {
            get {
                return ResourceManager.GetString("SuccessfulScheduledPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Payment of ${0} was unsuccessful on MAF acct # {1}. {2}For info reply HELP.
        /// </summary>
        public static string UnsuccessfulPayment {
            get {
                return ResourceManager.GetString("UnsuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear MAF Customer, Your scheduled payment of ${0} was unsuccessful on MAF account # {1}. Confirmation # is {2}. {reason}For info reply HELP.
        /// </summary>
        public static string UnsuccessfulScheduledPayment {
            get {
                return ResourceManager.GetString("UnsuccessfulScheduledPayment", resourceCulture);
            }
        }
    }
}
