//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.SolutionByText.GeneralWSServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReportInboundMessagesResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSReportInboundMessagesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSCarrierPhoneRow[] ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSCarrierPhoneRow[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCarrierPhoneRow", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSCarrierPhoneRow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InternationalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InvalidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LandlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarrierCode {
            get {
                return this.CarrierCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierCodeField, value) != true)) {
                    this.CarrierCodeField = value;
                    this.RaisePropertyChanged("CarrierCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Carrier {
            get {
                return this.CarrierField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierField, value) != true)) {
                    this.CarrierField = value;
                    this.RaisePropertyChanged("Carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool International {
            get {
                return this.InternationalField;
            }
            set {
                if ((this.InternationalField.Equals(value) != true)) {
                    this.InternationalField = value;
                    this.RaisePropertyChanged("International");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Invalid {
            get {
                return this.InvalidField;
            }
            set {
                if ((this.InvalidField.Equals(value) != true)) {
                    this.InvalidField = value;
                    this.RaisePropertyChanged("Invalid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool Landline {
            get {
                return this.LandlineField;
            }
            set {
                if ((this.LandlineField.Equals(value) != true)) {
                    this.LandlineField = value;
                    this.RaisePropertyChanged("Landline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCarrierLookupResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSCarrierLookupResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSCarrierPhoneRow[] ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSCarrierPhoneRow[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOrganizationTreeResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSOrganizationTreeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSOrganization ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSOrganization Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSOrganization", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSOrganization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgStructureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateAbbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactFNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactLNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactMobilePhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSOrganization[] organizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.GroupWS[] GroupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrgStructureName {
            get {
                return this.OrgStructureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgStructureNameField, value) != true)) {
                    this.OrgStructureNameField = value;
                    this.RaisePropertyChanged("OrgStructureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string OrgCode {
            get {
                return this.OrgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrgCodeField, value) != true)) {
                    this.OrgCodeField = value;
                    this.RaisePropertyChanged("OrgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CommunicationCode {
            get {
                return this.CommunicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationCodeField, value) != true)) {
                    this.CommunicationCodeField = value;
                    this.RaisePropertyChanged("CommunicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIDField, value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string StateAbbr {
            get {
                return this.StateAbbrField;
            }
            set {
                if ((object.ReferenceEquals(this.StateAbbrField, value) != true)) {
                    this.StateAbbrField = value;
                    this.RaisePropertyChanged("StateAbbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string ContactFName {
            get {
                return this.ContactFNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactFNameField, value) != true)) {
                    this.ContactFNameField = value;
                    this.RaisePropertyChanged("ContactFName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string ContactLName {
            get {
                return this.ContactLNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactLNameField, value) != true)) {
                    this.ContactLNameField = value;
                    this.RaisePropertyChanged("ContactLName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ContactPhoneNo {
            get {
                return this.ContactPhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneNoField, value) != true)) {
                    this.ContactPhoneNoField = value;
                    this.RaisePropertyChanged("ContactPhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ContactMobilePhoneNo {
            get {
                return this.ContactMobilePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactMobilePhoneNoField, value) != true)) {
                    this.ContactMobilePhoneNoField = value;
                    this.RaisePropertyChanged("ContactMobilePhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string ContactEmailID {
            get {
                return this.ContactEmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailIDField, value) != true)) {
                    this.ContactEmailIDField = value;
                    this.RaisePropertyChanged("ContactEmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSOrganization[] organization {
            get {
                return this.organizationField;
            }
            set {
                if ((object.ReferenceEquals(this.organizationField, value) != true)) {
                    this.organizationField = value;
                    this.RaisePropertyChanged("organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public MAF.SolutionByText.GeneralWSServiceReference.GroupWS[] Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupWS", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class GroupWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSubscriptionPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StackOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommunicationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.KeywordWS[] KeywordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupCode {
            get {
                return this.GroupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupCodeField, value) != true)) {
                    this.GroupCodeField = value;
                    this.RaisePropertyChanged("GroupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSubscriptionPublic {
            get {
                return this.IsSubscriptionPublicField;
            }
            set {
                if ((this.IsSubscriptionPublicField.Equals(value) != true)) {
                    this.IsSubscriptionPublicField = value;
                    this.RaisePropertyChanged("IsSubscriptionPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StackOrder {
            get {
                return this.StackOrderField;
            }
            set {
                if ((this.StackOrderField.Equals(value) != true)) {
                    this.StackOrderField = value;
                    this.RaisePropertyChanged("StackOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CommunicationCode {
            get {
                return this.CommunicationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CommunicationCodeField, value) != true)) {
                    this.CommunicationCodeField = value;
                    this.RaisePropertyChanged("CommunicationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public MAF.SolutionByText.GeneralWSServiceReference.KeywordWS[] Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordWS", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class KeywordWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyWordNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordNoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallbackURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int App_IdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscribedResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeywordTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsAutoSubscribeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeywordCode {
            get {
                return this.KeywordCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordCodeField, value) != true)) {
                    this.KeywordCodeField = value;
                    this.RaisePropertyChanged("KeywordCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string KeyWordName {
            get {
                return this.KeyWordNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyWordNameField, value) != true)) {
                    this.KeyWordNameField = value;
                    this.RaisePropertyChanged("KeyWordName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string KeywordNote {
            get {
                return this.KeywordNoteField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordNoteField, value) != true)) {
                    this.KeywordNoteField = value;
                    this.RaisePropertyChanged("KeywordNote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string KeywordResponse {
            get {
                return this.KeywordResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordResponseField, value) != true)) {
                    this.KeywordResponseField = value;
                    this.RaisePropertyChanged("KeywordResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CallbackURL {
            get {
                return this.CallbackURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CallbackURLField, value) != true)) {
                    this.CallbackURLField = value;
                    this.RaisePropertyChanged("CallbackURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int App_Identifier {
            get {
                return this.App_IdentifierField;
            }
            set {
                if ((this.App_IdentifierField.Equals(value) != true)) {
                    this.App_IdentifierField = value;
                    this.RaisePropertyChanged("App_Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string SubscribedResponse {
            get {
                return this.SubscribedResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscribedResponseField, value) != true)) {
                    this.SubscribedResponseField = value;
                    this.RaisePropertyChanged("SubscribedResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int KeywordTypeID {
            get {
                return this.KeywordTypeIDField;
            }
            set {
                if ((this.KeywordTypeIDField.Equals(value) != true)) {
                    this.KeywordTypeIDField = value;
                    this.RaisePropertyChanged("KeywordTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string KeywordType {
            get {
                return this.KeywordTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordTypeField, value) != true)) {
                    this.KeywordTypeField = value;
                    this.RaisePropertyChanged("KeywordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int IsAutoSubscribe {
            get {
                return this.IsAutoSubscribeField;
            }
            set {
                if ((this.IsAutoSubscribeField.Equals(value) != true)) {
                    this.IsAutoSubscribeField = value;
                    this.RaisePropertyChanged("IsAutoSubscribe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSVerificationTypeResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSVerificationTypeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerficationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerficationType {
            get {
                return this.VerficationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerficationTypeField, value) != true)) {
                    this.VerficationTypeField = value;
                    this.RaisePropertyChanged("VerficationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSReverseLookupResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSReverseLookupResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwner ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwner Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSPhoneOwner", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSPhoneOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrePaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerName NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerPhone PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreField, value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrePaid {
            get {
                return this.PrePaidField;
            }
            set {
                if ((object.ReferenceEquals(this.PrePaidField, value) != true)) {
                    this.PrePaidField = value;
                    this.RaisePropertyChanged("PrePaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerName Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public MAF.SolutionByText.GeneralWSServiceReference.WSPhoneOwnerPhone Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSPhoneOwnerName", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSPhoneOwnerName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CNAM {
            get {
                return this.CNAMField;
            }
            set {
                if ((object.ReferenceEquals(this.CNAMField, value) != true)) {
                    this.CNAMField = value;
                    this.RaisePropertyChanged("CNAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSPhoneOwnerAddress", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSPhoneOwnerAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreDirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AptTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AptNbrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Z4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Z4TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DPVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string House {
            get {
                return this.HouseField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseField, value) != true)) {
                    this.HouseField = value;
                    this.RaisePropertyChanged("House");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PreDir {
            get {
                return this.PreDirField;
            }
            set {
                if ((object.ReferenceEquals(this.PreDirField, value) != true)) {
                    this.PreDirField = value;
                    this.RaisePropertyChanged("PreDir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StrType {
            get {
                return this.StrTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.StrTypeField, value) != true)) {
                    this.StrTypeField = value;
                    this.RaisePropertyChanged("StrType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostDir {
            get {
                return this.PostDirField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDirField, value) != true)) {
                    this.PostDirField = value;
                    this.RaisePropertyChanged("PostDir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AptType {
            get {
                return this.AptTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AptTypeField, value) != true)) {
                    this.AptTypeField = value;
                    this.RaisePropertyChanged("AptType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AptNbr {
            get {
                return this.AptNbrField;
            }
            set {
                if ((object.ReferenceEquals(this.AptNbrField, value) != true)) {
                    this.AptNbrField = value;
                    this.RaisePropertyChanged("AptNbr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Z4 {
            get {
                return this.Z4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Z4Field, value) != true)) {
                    this.Z4Field = value;
                    this.RaisePropertyChanged("Z4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DPC {
            get {
                return this.DPCField;
            }
            set {
                if ((object.ReferenceEquals(this.DPCField, value) != true)) {
                    this.DPCField = value;
                    this.RaisePropertyChanged("DPC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CRTE {
            get {
                return this.CRTEField;
            }
            set {
                if ((object.ReferenceEquals(this.CRTEField, value) != true)) {
                    this.CRTEField = value;
                    this.RaisePropertyChanged("CRTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CNTY {
            get {
                return this.CNTYField;
            }
            set {
                if ((object.ReferenceEquals(this.CNTYField, value) != true)) {
                    this.CNTYField = value;
                    this.RaisePropertyChanged("CNTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Z4Type {
            get {
                return this.Z4TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Z4TypeField, value) != true)) {
                    this.Z4TypeField = value;
                    this.RaisePropertyChanged("Z4Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DPV {
            get {
                return this.DPVField;
            }
            set {
                if ((object.ReferenceEquals(this.DPVField, value) != true)) {
                    this.DPVField = value;
                    this.RaisePropertyChanged("DPV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Deliverable {
            get {
                return this.DeliverableField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverableField, value) != true)) {
                    this.DeliverableField = value;
                    this.RaisePropertyChanged("Deliverable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ValDate {
            get {
                return this.ValDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ValDateField, value) != true)) {
                    this.ValDateField = value;
                    this.RaisePropertyChanged("ValDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSPhoneOwnerPhone", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSPhoneOwnerPhone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelcoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ODateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DACodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneType {
            get {
                return this.PhoneTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneTypeField, value) != true)) {
                    this.PhoneTypeField = value;
                    this.RaisePropertyChanged("PhoneType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DID {
            get {
                return this.DIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DIDField, value) != true)) {
                    this.DIDField = value;
                    this.RaisePropertyChanged("DID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RecType {
            get {
                return this.RecTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RecTypeField, value) != true)) {
                    this.RecTypeField = value;
                    this.RaisePropertyChanged("RecType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TelcoName {
            get {
                return this.TelcoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TelcoNameField, value) != true)) {
                    this.TelcoNameField = value;
                    this.RaisePropertyChanged("TelcoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string IDate {
            get {
                return this.IDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IDateField, value) != true)) {
                    this.IDateField = value;
                    this.RaisePropertyChanged("IDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ODate {
            get {
                return this.ODateField;
            }
            set {
                if ((object.ReferenceEquals(this.ODateField, value) != true)) {
                    this.ODateField = value;
                    this.RaisePropertyChanged("ODate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PHV {
            get {
                return this.PHVField;
            }
            set {
                if ((object.ReferenceEquals(this.PHVField, value) != true)) {
                    this.PHVField = value;
                    this.RaisePropertyChanged("PHV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DACode {
            get {
                return this.DACodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DACodeField, value) != true)) {
                    this.DACodeField = value;
                    this.RaisePropertyChanged("DACode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSCustomerIDResponse", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class WSCustomerIDResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.CustomerID ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MAF.SolutionByText.GeneralWSServiceReference.CustomerID Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerID", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.CustomerIDName NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MAF.SolutionByText.GeneralWSServiceReference.CustomerIDPhone PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MAF.SolutionByText.GeneralWSServiceReference.CustomerIDName Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MAF.SolutionByText.GeneralWSServiceReference.CustomerIDPhone Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerIDName", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerIDName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CNAM {
            get {
                return this.CNAMField;
            }
            set {
                if ((object.ReferenceEquals(this.CNAMField, value) != true)) {
                    this.CNAMField = value;
                    this.RaisePropertyChanged("CNAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MName {
            get {
                return this.MNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MNameField, value) != true)) {
                    this.MNameField = value;
                    this.RaisePropertyChanged("MName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BusName {
            get {
                return this.BusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BusNameField, value) != true)) {
                    this.BusNameField = value;
                    this.RaisePropertyChanged("BusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerIDPhone", Namespace="http://SBTAPIService/DataContract/", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CustomerIDPhone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PHV {
            get {
                return this.PHVField;
            }
            set {
                if ((object.ReferenceEquals(this.PHVField, value) != true)) {
                    this.PHVField = value;
                    this.RaisePropertyChanged("PHV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SBTService/ServiceContracts/", ConfigurationName="GeneralWSServiceReference.IGroup")]
    public interface IGroup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCellularCarrier", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCellularCarrierResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSReportInboundMessagesResponse GetCellularCarrier(string securityToken, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCellularCarrier", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCellularCarrierResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSReportInboundMessagesResponse> GetCellularCarrierAsync(string securityToken, string[] phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCarrierLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCarrierLookupResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSCarrierLookupResponse GetCarrierLookup(string securityToken, string[] phone, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCarrierLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCarrierLookupResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSCarrierLookupResponse> GetCarrierLookupAsync(string securityToken, string[] phone, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetOrgTree", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetOrgTreeResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSOrganizationTreeResponse GetOrgTree(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetOrgTree", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetOrgTreeResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSOrganizationTreeResponse> GetOrgTreeAsync(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadVerificationType", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadVerificationTypeResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSVerificationTypeResponse ReadVerificationType(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReadVerificationType", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReadVerificationTypeResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSVerificationTypeResponse> ReadVerificationTypeAsync(string securityToken, string orgCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReverseLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReverseLookupResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSReverseLookupResponse ReverseLookup(string securityToken, string orgCode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/ReverseLookup", ReplyAction="http://SBTService/ServiceContracts/IGroup/ReverseLookupResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSReverseLookupResponse> ReverseLookupAsync(string securityToken, string orgCode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCustomerID", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCustomerIDResponse")]
        MAF.SolutionByText.GeneralWSServiceReference.WSCustomerIDResponse GetCustomerID(string securityToken, string orgCode, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SBTService/ServiceContracts/IGroup/GetCustomerID", ReplyAction="http://SBTService/ServiceContracts/IGroup/GetCustomerIDResponse")]
        System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSCustomerIDResponse> GetCustomerIDAsync(string securityToken, string orgCode, string phone);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupChannel : MAF.SolutionByText.GeneralWSServiceReference.IGroup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupClient : System.ServiceModel.ClientBase<MAF.SolutionByText.GeneralWSServiceReference.IGroup>, MAF.SolutionByText.GeneralWSServiceReference.IGroup {
        
        public GroupClient() {
        }
        
        public GroupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSReportInboundMessagesResponse GetCellularCarrier(string securityToken, string[] phone) {
            return base.Channel.GetCellularCarrier(securityToken, phone);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSReportInboundMessagesResponse> GetCellularCarrierAsync(string securityToken, string[] phone) {
            return base.Channel.GetCellularCarrierAsync(securityToken, phone);
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSCarrierLookupResponse GetCarrierLookup(string securityToken, string[] phone, string orgCode) {
            return base.Channel.GetCarrierLookup(securityToken, phone, orgCode);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSCarrierLookupResponse> GetCarrierLookupAsync(string securityToken, string[] phone, string orgCode) {
            return base.Channel.GetCarrierLookupAsync(securityToken, phone, orgCode);
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSOrganizationTreeResponse GetOrgTree(string securityToken, string orgCode) {
            return base.Channel.GetOrgTree(securityToken, orgCode);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSOrganizationTreeResponse> GetOrgTreeAsync(string securityToken, string orgCode) {
            return base.Channel.GetOrgTreeAsync(securityToken, orgCode);
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSVerificationTypeResponse ReadVerificationType(string securityToken, string orgCode) {
            return base.Channel.ReadVerificationType(securityToken, orgCode);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSVerificationTypeResponse> ReadVerificationTypeAsync(string securityToken, string orgCode) {
            return base.Channel.ReadVerificationTypeAsync(securityToken, orgCode);
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSReverseLookupResponse ReverseLookup(string securityToken, string orgCode, string phone) {
            return base.Channel.ReverseLookup(securityToken, orgCode, phone);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSReverseLookupResponse> ReverseLookupAsync(string securityToken, string orgCode, string phone) {
            return base.Channel.ReverseLookupAsync(securityToken, orgCode, phone);
        }
        
        public MAF.SolutionByText.GeneralWSServiceReference.WSCustomerIDResponse GetCustomerID(string securityToken, string orgCode, string phone) {
            return base.Channel.GetCustomerID(securityToken, orgCode, phone);
        }
        
        public System.Threading.Tasks.Task<MAF.SolutionByText.GeneralWSServiceReference.WSCustomerIDResponse> GetCustomerIDAsync(string securityToken, string orgCode, string phone) {
            return base.Channel.GetCustomerIDAsync(securityToken, orgCode, phone);
        }
    }
}
