//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAF.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineUser
    {
        public string AcctNo { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> SecurityID { get; set; }
        public string Answer { get; set; }
        public string CCAuthorized { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<byte> SecurityID2 { get; set; }
        public string Answer2 { get; set; }
        public Nullable<byte> SecurityID3 { get; set; }
        public string Answer3 { get; set; }
        public string BitReset { get; set; }
        public string ProfilePicture { get; set; }
    }
}
